### ISSUE TITLE
Minor Issue: Can't see Container names

### ISSUE THREAD

**Issue by jquacinella** [yadutaf/ctop#21]
Great tool you wrote. Quick note: When installing via pip, using pip install ctop, the program cannot resolve container names and will only show the numeric id. When installing via your wget command example, ctop can. Is there a slight difference in what is released on pypi and on github?

Thanks!

**Comment by yadutaf** [comment]
As a matter of fact there is one big difference: Pypi release is completely outdated... I'll update it

**Comment by yadutaf** [comment]
Done! Thanks for noticing.

**Comment by jquacinella** [comment]
Rock, thanks!

**Comment by kunday** [comment]
@yadutaf I'm still having the same issue with the pip package and docker image...

**Comment by josephpage** [comment]
Same issue with the Docker image

**Comment by yadutaf** [comment]
The docker image does not have acces to the docker daemon / cli. To Mayke it work you'd need to expose the docker CLI and socket in the container hence reducing to nil the whole benefit of container (ie: isolation)

**Comment by yadutaf** [comment]
To elaborate on that, ctop is a single, minimalist, self-contained python file. It is very lean compared to a Docker image.

**Comment by josephpage** [comment]
It works with adding `-v /usr/local/bin/docker:/usr/local/bin/docker`.

I work on a Mac, and I have this in my bash_profile : 
```bash
alias ctop="docker run -it --rm \
                      --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro \
                      --volume=/var/run/docker.sock:/var/run/docker.sock \
                      --volume=$(which docker):/usr/local/bin/docker \
                      yadutaf/ctop --tree \
                         --columns='processes,memory,cpu-sys,cpu-user,blkio,cpu-time,name'"
```

I just prefer to have everything inside containers 😍
